### ISSUE TITLE
Please explain how to use this library in Angular please 😄 

### ISSUE THREAD

**Issue by alizhan1** [heavy-duty/platform#120]
### Description

...

### Proposed solution

...

### Alternatives considered

...

**Comment by danmt** [comment]
Hey there, what are you exactly looking for? We have a few packages... Are you looking to use Bulldozer?

**Comment by alizhan1** [comment]
Hey, @danmt ! How are you doing? I was trying to find how to use the wallet adapter library, but I could not find any docs. I was hoping someone can explain it hehe.

**Comment by danmt** [comment]
All good! So, yeah... there are no docs atm, but there are a few examples I can point you to. This project integrated it for the hackathon [repo](https://github.com/Disco-Foundation/event-manager-platform).

Here's the list of dependencies you'll need :

 - "@angular/core": "13.2.2",
 - "@heavy-duty/rxjs": "0.1.0",
 -  "rxjs": "7.5.2",
 -  "@ngrx/component-store": "13.0.2",
 -  "@solana/web3.js": "1.36.0",
 -  "@solana/wallet-adapter-base": "0.9.5"
 -  "@heavy-duty/wallet-adapter": "0.2.2"
 
 Your app will need these polyfills:
 
 ```typescript
 import { Buffer } from 'buffer';
 import 'zone.js'; // Included with Angular CLI.
 
 (window as any).global = window;
 (window as any).global.Buffer = Buffer;
 (window as any).process = {
   version: '',
   node: false,
   env: false,
 };
 ```

And you'll need to have a custom webpack configuration like this:

```javascript
module.exports = (config) => {
  config.resolve.fallback = {
    path: false,
    fs: false,
    os: false,
    crypto: false,
    process: false,
    util: false,
    assert: false,
    stream: false,
  };

  return config;
};
```
 
This is the actual [Angular app where all this gets used together](https://github.com/Disco-Foundation/event-manager-platform/tree/main/apps/event-manager-web-client).

Don't forget to tell the compiler to use the custom webpack by [using the right executor for build](https://github.com/Disco-Foundation/event-manager-platform/blob/main/apps/event-manager-web-client/project.json#L8) and [using the right executor for serve](https://github.com/Disco-Foundation/event-manager-platform/blob/main/apps/event-manager-web-client/project.json#L61), also you need to tell the compiler  [where the custom webpack config file goes](https://github.com/Disco-Foundation/event-manager-platform/blob/main/apps/event-manager-web-client/project.json#L24).

So that's it with the boring configuration, you need now to [set up the wallet adapter in your app module](https://github.com/Disco-Foundation/event-manager-platform/blob/main/apps/event-manager-web-client/src/app/app.module.ts#L22) and [set the wallets you want to use](https://github.com/Disco-Foundation/event-manager-platform/blob/main/libs/event-manager/web-client/shell/src/lib/shell.component.ts#L95).

Having all that in place your component tree has access through DI to the [WalletStore ComponentStore](https://github.com/heavy-duty/platform/blob/master/libs/wallet-adapter/data-access/src/lib/wallet.store.ts), which you can think of it as a service that exposes some observable that allow you to do all the common stuff (check wallet connection, wallet public key, etc) and methods to sign and send TXs.

I know it's a lot to digest, I've been planning to write some docs and a generator for easier setup but never find a chance to do it. Feel free to drop any questions about issues you find, all that helps us write the docs later.

**Comment by alizhan1** [comment]
@danmt maaan, I think this is most detailed explanation I have ever got. Thanks you very much! I will try it out tomorrow. I would be glad to help writing the README, if I get it working haha

**Comment by danmt** [comment]
If you put in the work for the README, I got your back for any questions/feedback and I'd be more than happy to review it. Just remember that this explanation will just get you the business logic of dealing with wallets. Once you set that up, you'll have to do the UI part, which also, feel free to ask questions.

**Comment by danmt** [comment]
Huh, being honest I didn't know it would work with `ng`... Unless you have a strong reason to use the Angular CLI I'd recommend you to take a look at Nx, I know it's a bit overwhelming at first but it's totally worth it IMHO.

I can think of a few options for your problem, there's an Angular CLI-compatible option called [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack), it's almost the same, you just have to change the value of the builder attribute. 

Also, it seems like your customWebpackConfig is pointing to the dist folder, I'm not sure if this is something specific to the environments I've used in the past but the webpack config is not auto-added to the dist. You have to either include it yourself in the dist or using a reference to the config in it's original place (i.e. `apps/web3-playground/webpack.config.js`)

**Comment by alizhan1** [comment]
Hey, man! I finally managed it to work using ng
basically, it is exactly the same as you said
serve:
`
"serve": {
  "builder": "@angular-builders/custom-webpack:dev-server",
  "configurations": {
    "production": {
      "browserTarget": "web3-playground:build:production"
    },
    "development": {
      "browserTarget": "web3-playground:build:development"
    }
  },
  "defaultConfiguration": "development"
},
`
build:
`
"build": {
  "builder": "@angular-builders/custom-webpack:browser",
  "options": {
    "outputPath": "dist/web3-playground",
    "index": "src/index.html",
    "main": "src/main.ts",
    "polyfills": "src/polyfills.ts",
    "tsConfig": "tsconfig.app.json",
    "assets": [
      "src/favicon.ico",
      "src/assets"
    ],
    "styles": [
      "./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css",
      "src/styles.css"
    ],
    "scripts": [],
    "customWebpackConfig": {
      "path": "webpack.config.js"
    }
  }
`

**Comment by danmt** [comment]
I'm glad you made it to the end of the tunnel. The wallet adapter also comes with an Angular Material UI kit with the common widgets you need to deal with wallets. In case you're using another Design System, you can use the CDK which has all the directives and re-usable things I needed when writing the Material UI package.

I'm excited to see that README!

**Comment by alizhan1** [comment]
[README.md](https://github.com/heavy-duty/platform/files/8371511/README.md)

**Comment by alizhan1** [comment]
> I'm glad you made it to the end of the tunnel. The wallet adapter also comes with an Angular Material UI kit with the common widgets you need to deal with wallets. In case you're using another Design System, you can use the CDK which has all the directives and re-usable things I needed when writing the Material UI package.
> 
> I'm excited to see that README!

Man, I will be glad if you can send me some examples of how to use those reusable uis

**Comment by danmt** [comment]
Good work man! Do you mind creating a PR? That makes it easier to review it

**Comment by alizhan1** [comment]
sure

**Comment by alizhan1** [comment]
I think I cannot create PR, nor branch as I am not collaborator in this repo ;)

**Comment by alizhan1** [comment]
it is all good man, no worries https://github.com/heavy-duty/platform/pull/123/commits
